/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OperateRouteImport } from './routes/operate'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BuildRouteImport } from './routes/build'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OperateRoute = OperateRouteImport.update({
  id: '/operate',
  path: '/operate',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/grow': typeof GrowRoute
  '/learn': typeof LearnRoute
  '/manager': typeof ManagerRoute
  '/operate': typeof OperateRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/grow': typeof GrowRoute
  '/learn': typeof LearnRoute
  '/manager': typeof ManagerRoute
  '/operate': typeof OperateRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/grow': typeof GrowRoute
  '/learn': typeof LearnRoute
  '/manager': typeof ManagerRoute
  '/operate': typeof OperateRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/build'
    | '/career'
    | '/grow'
    | '/learn'
    | '/manager'
    | '/operate'
    | '/profile'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/build'
    | '/career'
    | '/grow'
    | '/learn'
    | '/manager'
    | '/operate'
    | '/profile'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/build'
    | '/career'
    | '/grow'
    | '/learn'
    | '/manager'
    | '/operate'
    | '/profile'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildRoute: typeof BuildRoute
  CareerRoute: typeof CareerRoute
  GrowRoute: typeof GrowRoute
  LearnRoute: typeof LearnRoute
  ManagerRoute: typeof ManagerRoute
  OperateRoute: typeof OperateRoute
  ProfileRoute: typeof ProfileRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operate': {
      id: '/operate'
      path: '/operate'
      fullPath: '/operate'
      preLoaderRoute: typeof OperateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildRoute: BuildRoute,
  CareerRoute: CareerRoute,
  GrowRoute: GrowRoute,
  LearnRoute: LearnRoute,
  ManagerRoute: ManagerRoute,
  OperateRoute: OperateRoute,
  ProfileRoute: ProfileRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
